###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
"auditStatus": "202002",
"courseName":""
}

<> 2024-05-16T195459.200.json


###
GET http://localhost:63040/content/course/{{courseId}}



